name: Backend Build

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build:
    if: "contains(github.event.head_commit.message, '[backend-build]')"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a simple check
      run: |
        echo "Backend build triggered successfully!"
        echo "Commit message: ${{ github.event.head_commit.message }}"