name: Backend Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: "contains(github.event.head_commit.message, 'backend build') && !contains(github.event.head_commit.message, 'frontend build')"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run a simple check
      run: |
        echo "Backend build triggered successfully!"
        echo "Commit message: ${{ github.event.head_commit.message }}"